### PR TITLE
Re-work exception handling on LDAP lookups (fix #55)

### LINKED ISSUE #55: Confusing LDAP message about "unique" user
@stickm points out that:

```
Default choice on create user: XXX (ome.conditions.ApiUsageException: Cannot find unique user DistinguishedName: found=1)
```

is confusing. Looking at https://github.com/ome/omero-server/blob/master/src/main/java/ome/logic/LdapImpl.java#L200, there are a _number_ of code paths that will throw that aren't unique issues. Each should throw a separate exception.

### PR DESCRIPTION
**Pull request by joshmoore**
Rather than use the same "Cannot find unique distinguished"
exception for all code paths, throw early with a different
message for each case.

cc: @stick @mtbc

### CODE REVIEW

File: src/main/java/ome/logic/LdapImpl.java [hunk 1]
```diff
@@ -197,37 +197,54 @@ private Experimenter mapUserName(String username, PersonContextMapper mapper) {
...
-                }
-            }
+        if (p.size() != 1) {
+            throw new ApiUsageException(
+                    "Cannot find unique user DistinguishedName: found=" + p.size());
+        }
+
+        if (p.get(0) == null) {
+            throw new ApiUsageException(
+                    "Returned Experiment is null!");
```
Comment (mtbc) [inline src/main/java/ome/logic/LdapImpl.java]: Experimenter?

**Comment by mtbc** [comment]
Should all the exceptions mention the user or group name?

**Comment by joshmoore** [comment]
> Should all the exceptions mention the user or group name?

Done.
