### PR TITLE
Ensure that the event context has sudoer.omeName loaded.

### LINKED ISSUE #70: sudo fails for read-only server
`SessionProviderInMemory.executeUpdate` for sudo sessions runs,
```java
session.setSudoer(new Experimenter(sudoerId, false));
```
but `SimpleEventContext.copy` expects to use `getCurrentSudoerName()` so when the security system is first trying to check and initialize the context an "Object unloaded" is thrown on the sudoer.

### PR DESCRIPTION
**Pull request by mtbc**
Allows sudo sessions even on read-only servers. Fixes #70.

### CODE REVIEW

File: src/main/java/ome/security/basic/BasicSecuritySystem.java [hunk 1]
```diff
@@ -374,6 +377,23 @@ public void loadEventContext(boolean isReadOnly, boolean isClose) {
             ec = (EventContext) ste.sessionContext;
         }
 
+        // Ensure that sudoer has name loaded for SimpleEventContext.copy
+        if (ec instanceof SessionContext) {
+            final ome.model.meta.Session session = ((SessionContext) ec).getSession();
+            Experimenter sudoer = session.getSudoer();
+            if (!(sudoer == null || sudoer.isLoaded())) {
```
Comment (joshmoore) [inline src/main/java/ome/security/basic/BasicSecuritySystem.java]: Do you know when `sudoer` _is_ loaded?

File: src/main/java/ome/security/basic/BasicSecuritySystem.java [hunk 2]
```diff
@@ -374,6 +377,23 @@ public void loadEventContext(boolean isReadOnly, boolean isClose) {
...
+                final Long sudoerId = sudoer.getId();
+                final IQuery iQuery = sf.getQueryService();
+                final String hql = "SELECT omeName FROM Experimenter WHERE id = :id";
+                final Parameters params = new Parameters().addId(sudoerId);
+                final List<Object[]> result = iQuery.projection(hql, params);
+                final String sudoerName = (String) result.get(0)[0];
+                sudoer = new Experimenter(sudoerId, true);
+                sudoer.setOmeName(sudoerName);
```
Comment (joshmoore) [inline src/main/java/ome/security/basic/BasicSecuritySystem.java]: This is technically a no-no. By saying, "true" you're saying that this object is hydrated but only setting one field. If this were to leak into another context and be saved, the DB would throw due to missing fields.

It might be safer to follow the idiom on line 406 and `admin.userProxy(sudoerId);`. That will then be (de-)serialized as with the rest of the system.

File: src/main/java/ome/security/basic/BasicSecuritySystem.java (hunk 1 above)
Comment (mtbc) [reply src/main/java/ome/security/basic/BasicSecuritySystem.java]: I don't I'm afraid.

Comment (mtbc) [reply src/main/java/ome/security/basic/BasicSecuritySystem.java]: I don't see that it's different in read-only mode but that would also be a thing to watch out for.

Comment (mtbc) [reply src/main/java/ome/security/basic/BasicSecuritySystem.java]: (Possibly with read-only trying hard not to keep an accumulation of lots of session data all stored in memory.)

**Comment by joshmoore** [comment]
Changes look fine. Is there a read-only server deployed anywhere with this change?

**Comment by mtbc** [comment]
Not as far as I know.

**Comment by joshmoore** [comment]
Testing via https://github.com/ome/docker-example-omero-readonly -- will propose for https://github.com/ome/omero-deployment-examples once things are ironed out.

**Comment by joshmoore** [comment]
1. Start docker with default 5.6

<details><summary>2. Create test group & user in readwrite and test sudo :+1:</summary>

```
jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose exec omeroserver-readwrite bash
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero group add test
Server: [localhost:4064]
Username: [omero-server]root
Password:
Created session for root@localhost:4064. Idle timeout: 10 min. Current group: system
Added group test (id=3) with permissions rw----
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero user add test test test test
Using session for root@localhost:4064. Idle timeout: 10 min. Current group: system
Please enter password for your new user (test):
Please re-enter password for your new user (test):
Added user test (id=2) with password
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero login --sudo=root test@localhost
Password for root:
Created session for test@localhost:4064. Idle timeout: 10 min. Current group: test
bash-4.2$ exit
```

</details>

<details><summary>3. Test sudo in read-only, see failure as expected :+1:</summary>

```
[jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose exec omeroserver-readonly bash
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero login --sudo=root test@localhost
Password for root:
InternalException: Failed to connect: exception ::omero::InternalException
{
    serverStackTrace = ome.conditions.InternalException:  Wrapped Exception: (java.lang.IllegalStateException):
Object unloaded:ome.model.meta.Experimenter:Id_0
	at ome.model.meta.Experimenter.errorIfUnloaded(Experimenter.java:1348)
	at ome.model.meta.Experimenter.getOmeName(Experimenter.java:579)
	at ome.services.sessions.SessionContextImpl.getCurrentSudoerName(SessionContextImpl.java:133)
	at ome.system.SimpleEventContext.copy(SimpleEventContext.java:91)
	at ome.security.basic.BasicEventContext.copyContext(BasicEventContext.java:106)
	at ome.security.basic.BasicEventContext.checkAndInitialize(BasicEventContext.java:110)
	at ome.security.basic.CurrentDetails.checkAndInitialize(CurrentDetails.java:317)
	at ome.security.basic.BasicSecuritySystem.loadEventContext(BasicSecuritySystem.java:378)
	at ome.security.basic.EventHandler.doLogin(EventHandler.java:210)
	at ome.security.basic.EventHandler.invoke(EventHandler.java:146)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy91.getEventContext(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy91.getEventContext(Unknown Source)
    ports:
	at sun.reflect.GeneratedMethodAccessor268.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172)
	at ome.services.throttling.Callback.run(Callback.java:56)
	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140)
	at ome.services.blitz.impl.AdminI.getEventContext_async(AdminI.java:236)
	at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at omero.cmd.CallContext.invoke(CallContext.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy92.getEventContext_async(Unknown Source)
	at omero.api._IAdminTie.getEventContext_async(_IAdminTie.java:222)
	at omero.api._IAdminDisp.___getEventContext(_IAdminDisp.java:2110)
	at omero.api._IAdminDisp.__dispatch(_IAdminDisp.java:2296)
	at IceInternal.Incoming.invoke(Incoming.java:221)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
	at Ice.ConnectionI.message(ConnectionI.java:1056)
	at IceInternal.ThreadPool.run(ThreadPool.java:395)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
	at java.lang.Thread.run(Thread.java:748)

    serverExceptionClass = ome.conditions.InternalException
    message =  Wrapped Exception: (java.lang.IllegalStateException):
Object unloaded:ome.model.meta.Experimenter:Id_0
}
!! 01/29/20 07:38:43.201 error: communicator not destroyed during global destruction.bash-4.2$ exit
```

</details>

<details><summary>4. Restart with new merge-ci-based images and re-test :-1:</summary>

```
[jamoore@idr1-slot2 docker-example-omero-readonly]$ vi docker-compose.yml
[jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose down
Stopping dockerexampleomeroreadonly_omeroserver-readonly_1  ... done
Stopping dockerexampleomeroreadonly_database_1              ... done
Stopping dockerexampleomeroreadonly_omeroweb_1              ... done
Stopping dockerexampleomeroreadonly_omeroserver-readwrite_1 ... done
Removing dockerexampleomeroreadonly_omeroserver-readonly_1  ... done
Removing dockerexampleomeroreadonly_database_1              ... done
Removing dockerexampleomeroreadonly_omeroweb_1              ... done
Removing dockerexampleomeroreadonly_omeroserver-readwrite_1 ... done
Removing network dockerexampleomeroreadonly_omero
[jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose up -d
Creating network "dockerexampleomeroreadonly_omero" with the default driver
Creating dockerexampleomeroreadonly_omeroserver-readwrite_1 ...
Creating dockerexampleomeroreadonly_database_1 ...
Creating dockerexampleomeroreadonly_omeroweb_1 ...
Creating dockerexampleomeroreadonly_omeroserver-readwrite_1
Creating dockerexampleomeroreadonly_database_1
Creating dockerexampleomeroreadonly_database_1 ... done
Creating dockerexampleomeroreadonly_omeroserver-readonly_1 ...
Creating dockerexampleomeroreadonly_omeroserver-readonly_1 ... done
[jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose exec omeroserver-readonly bash
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero login --sudo=root test@localhost
Password for root:
InternalException: Failed to connect: exception ::omero::InternalException
{
    serverStackTrace = ome.conditions.InternalException:  Wrapped Exception: (org.springframework.orm.hibernate3.HibernateSystemException):
A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks; nested exception is org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:709)
	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:416)
	at org.springframework.orm.hibernate3.HibernateInterceptor.invoke(HibernateInterceptor.java:125)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.tools.hibernate.ProxyCleanupFilter$Interceptor.invoke(ProxyCleanupFilter.java:249)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.util.ServiceHandler.invoke(ServiceHandler.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy91.getEventContext(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at ome.security.basic.BasicSecurityWiring.invoke(BasicSecurityWiring.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at ome.services.blitz.fire.AopContextInitializer.invoke(AopContextInitializer.java:43)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy91.getEventContext(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ome.services.blitz.util.IceMethodInvoker.invoke(IceMethodInvoker.java:172)
	at ome.services.throttling.Callback.run(Callback.java:56)
	at ome.services.throttling.InThreadThrottlingStrategy.callInvokerOnRawArgs(InThreadThrottlingStrategy.java:56)
	at ome.services.blitz.impl.AbstractAmdServant.callInvokerOnRawArgs(AbstractAmdServant.java:140)
	at ome.services.blitz.impl.AdminI.getEventContext_async(AdminI.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at omero.cmd.CallContext.invoke(CallContext.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy92.getEventContext_async(Unknown Source)
	at omero.api._IAdminTie.getEventContext_async(_IAdminTie.java:222)
	at omero.api._IAdminDisp.___getEventContext(_IAdminDisp.java:2110)
	at omero.api._IAdminDisp.__dispatch(_IAdminDisp.java:2296)
	at IceInternal.Incoming.invoke(Incoming.java:221)
	at Ice.ConnectionI.invokeAll(ConnectionI.java:2536)
	at Ice.ConnectionI.dispatch(ConnectionI.java:1145)
	at Ice.ConnectionI.message(ConnectionI.java:1056)
	at IceInternal.ThreadPool.run(ThreadPool.java:395)
	at IceInternal.ThreadPool.access$300(ThreadPool.java:12)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:832)
	at java.lang.Thread.run(Thread.java:748)

    serverExceptionClass = ome.conditions.InternalException
    message =  Wrapped Exception: (org.springframework.orm.hibernate3.HibernateSystemException):
A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks; nested exception is org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks
}
!! 01/29/20 07:40:04.724 error: communicator not destroyed during global destruction.bash-4.2$
```

</details>

Fails with:

```
InternalException: Failed to connect: exception ::omero::InternalException
{
    serverStackTrace = ome.conditions.InternalException:  Wrapped Exception: (org.springframework.orm.hibernate3.HibernateSystemException):
A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks; nested exception is org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: ome.model.meta.Experimenter.annotationLinks
	at 
```

**Comment by mtbc** [comment]
Ah, that'll be why I had things as they were then, reverting the latest.

**Comment by mtbc** [comment]
My understanding of the code is that this dodgy instance is promptly dumped anyway in favor of a copy thereof.

**Comment by joshmoore** [comment]
After rebuilding my docker image,
```
[jamoore@idr1-slot2 docker-example-omero-readonly]$ docker-compose exec omeroserver-readonly bash
bash-4.2$ /opt/omero/server/OMERO.server/bin/omero login --sudo=root test@localhost
Password for root:
Created session for test@localhost:4064. Idle timeout: 10 min. Current group: test
```

:+1: (Note: this also means that we have no testing of this code path.)
